# Generated by Django 3.0.6 on 2020-05-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(help_text='学生姓名', max_length=64)),
                ('s_sex', models.IntegerField(choices=[(0, '男'), (1, '女')], help_text='性别')),
                ('s_phone', models.CharField(help_text='手机号', max_length=11)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
