# Generated by Django 3.0.6 on 2020-05-31 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(help_text='课程名', max_length=64, verbose_name='课程名')),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='Stu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(help_text='学生姓名', max_length=64, verbose_name='学生姓名')),
                ('s_sex', models.CharField(choices=[(0, '男'), (1, '女')], help_text='性别：0-男；1-女', max_length=1, verbose_name='性别')),
                ('s_age', models.PositiveIntegerField(default=0, help_text='年龄', verbose_name='年龄')),
                ('s_dept', models.CharField(help_text='专业', max_length=64, verbose_name='专业')),
                ('course', models.ManyToManyField(db_table='stu_course', related_name='course_student', to='app01.Course')),
            ],
            options={
                'db_table': 'stu',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(help_text='老师姓名', max_length=64, verbose_name='老师姓名')),
            ],
            options={
                'db_table': 'teacher',
            },
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_card', models.CharField(max_length=18, unique=True, verbose_name='身份证号')),
                ('s_phone', models.CharField(help_text='手机号', max_length=11, unique=True)),
                ('s_addr', models.CharField(help_text='家庭住址', max_length=128, verbose_name='家庭住址')),
                ('s_id', models.OneToOneField(db_column='s_id', on_delete=django.db.models.deletion.CASCADE, related_name='stu_info_stu', to='app01.Stu')),
            ],
            options={
                'db_table': 'student_info',
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0, help_text='成绩', verbose_name='成绩')),
                ('c_id', models.ForeignKey(db_column='c_id', help_text='学生编号', on_delete=django.db.models.deletion.CASCADE, related_name='course_score', to='app01.Course')),
                ('s_id', models.ForeignKey(db_column='s_id', help_text='学生编号', on_delete=django.db.models.deletion.CASCADE, related_name='stu_score', to='app01.Stu')),
            ],
            options={
                'db_table': 'score',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='t_id',
            field=models.ForeignKey(db_column='t_id', help_text='老师编号', on_delete=django.db.models.deletion.CASCADE, related_name='teacher_course', to='app01.Teacher'),
        ),
    ]
